import Head from "next/head";
// import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about">About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href="">
          <h2>Events in London</h2>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil in
            officiis laborum eaque a dolorem, quidem eligendi earum aspernatur
            repellendus voluptate unde facilis quam harum neque eos asperiores,
            eius ipsa!
          </p>
        </a>
        <a href="">
          <h2>Events in San Franciso</h2>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil in
            officiis laborum eaque a dolorem, quidem eligendi earum aspernatur
            repellendus voluptate unde facilis quam harum neque eos asperiores,
            eius ipsa!
          </p>
        </a>
        <a href="">
          <h2>Events in New York</h2>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil in
            officiis laborum eaque a dolorem, quidem eligendi earum aspernatur
            repellendus voluptate unde facilis quam harum neque eos asperiores,
            eius ipsa!
          </p>
        </a>
      </main>
      <footer className={styles.footer}>
        <p>2023 - NextJs Events Project</p>
      </footer>
    </>
  );
}
